module.exports = {
    AjaxUploader: require('./AjaxUploader.js'),
    AutoComplete: require('./AutoComplete.js'),
    Checkbox: require('./Checkbox.js'),
    CheckboxGroup: require('./CheckboxGroup.js'),
    DropdownSelector: require('./DropdownSelector.js'),
    DateTime: require('./DateTime.js'),
    FileUploader: require('./FileUploader.js'),
    FormTitle: require('./FormTitle.js'),
    ImageUploader: require('./ImageUploader.js'),
    Radio: require('./Radio.js'),
    RichEditor: require('./RichEditor.js'),
    RichSelector: require('./RichSelector.js'),
    Select: require('./Select.js'),
    ImageUploader: require('./ImageUploader.js'),
    Menu: require('./Menu.js'),
    MultiInput: require('./MultiInput.js'),
    OrderCode: require('./OrderCode.js'),
    Form: require('./Form.js'),
    FormItem: require('./FormItem.js'),
    FileUploader: require('./FileUploader.js'),
    Input: require('./Input.js'),
    Label: require('./Label.js'),
    Textarea: require('./Textarea.js'),
    ToggleSwitch: require('./ToggleSwitch.js')
}
